# link to the problem - https://leetcode.com/problems/find-the-difference/

# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.

# link to submission - https://leetcode.com/submissions/detail/707041966/

import collections

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        diff = list((collections.Counter(t) - collections.Counter(s)))

        return diff[0]


